### ISSUE TITLE
Timezone Error 

### ISSUE THREAD

**Issue by danrovito** [caxy/public-school-api#1]
I'm not 100% sure if this is code or server related but when I try to use an endpoint on my install it retrieves the data but also send this error

Warning: DateTime::createFromFormat(): Invalid date.timezone value 'AMERICA\NEWYORK', we selected the timezone 'UTC' for now. in /Users/dan/Sites/public-school-api/vendor/symfony/http-foundation/Response.php on line 205

**Comment by jschroed91** [comment]
Hi @danrovito - that seems like a server config issue - the time zone value for New York should be America/New_York (you're missing the underscore). At least according to this page http://php.net/manual/en/timezones.america.php

Hopefully that works!

**Comment by danrovito** [comment]
Thank you.
